version: '3.4'


volumes:
  weaviate_data:


services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.4
    ports:
    - 9000:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      # ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
 
  vector_db_interface:
    container_name: vector-db-interface
    build: 
      context: ./vector_db_interface
    env_file: .env
    ports:
      - "50053:50051"
    depends_on:
      - "weaviate"
    restart: always
  
  chat_interface:
    container_name: chat-interface
    build: 
      context: ./chat_interface
    env_file: .env
    ports:
      - "50055:50055"
    depends_on:
      - "weaviate"
    restart: always