# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"*\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\"\xd0\x01\n\x0eMessageRequest\x12@\n\ruser_metadata\x18\x01 \x03(\x0b\x32).chatbot.MessageRequest.UserMetadataEntry\x12\x12\n\ncategories\x18\x02 \x03(\t\x12\"\n\x08messages\x18\x03 \x03(\x0b\x32\x10.chatbot.Message\x12\x0f\n\x07timeout\x18\x04 \x01(\x05\x1a\x33\n\x11UserMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"_\n\x0fMessageResponse\x12\x18\n\x10response_message\x18\x01 \x01(\t\x12\x17\n\x0fused_categories\x18\x02 \x03(\t\x12\x19\n\x11used_document_ids\x18\x03 \x03(\t2J\n\x0b\x43hatService\x12;\n\x06\x41nswer\x12\x17.chatbot.MessageRequest\x1a\x18.chatbot.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST_USERMETADATAENTRY']._loaded_options = None
  _globals['_MESSAGEREQUEST_USERMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=26
  _globals['_MESSAGE']._serialized_end=68
  _globals['_MESSAGEREQUEST']._serialized_start=71
  _globals['_MESSAGEREQUEST']._serialized_end=279
  _globals['_MESSAGEREQUEST_USERMETADATAENTRY']._serialized_start=228
  _globals['_MESSAGEREQUEST_USERMETADATAENTRY']._serialized_end=279
  _globals['_MESSAGERESPONSE']._serialized_start=281
  _globals['_MESSAGERESPONSE']._serialized_end=376
  _globals['_CHATSERVICE']._serialized_start=378
  _globals['_CHATSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
