# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vector_db_pb2 as vector__db__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class VectorDBServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddArticles = channel.unary_unary(
                '/vector_db.VectorDBService/AddArticles',
                request_serializer=vector__db__pb2.AddArticlesRequest.SerializeToString,
                response_deserializer=vector__db__pb2.AddArticlesResponse.FromString,
                _registered_method=True)
        self.GetArticles = channel.unary_unary(
                '/vector_db.VectorDBService/GetArticles',
                request_serializer=vector__db__pb2.GetArticlesRequest.SerializeToString,
                response_deserializer=vector__db__pb2.GetArticlesResponse.FromString,
                _registered_method=True)
        self.RemoveArticles = channel.unary_unary(
                '/vector_db.VectorDBService/RemoveArticles',
                request_serializer=vector__db__pb2.RemoveArticlesRequest.SerializeToString,
                response_deserializer=vector__db__pb2.RemoveArticlesResponse.FromString,
                _registered_method=True)
        self.UpdateArticles = channel.unary_unary(
                '/vector_db.VectorDBService/UpdateArticles',
                request_serializer=vector__db__pb2.UpdateArticlesRequest.SerializeToString,
                response_deserializer=vector__db__pb2.UpdateArticlesResponse.FromString,
                _registered_method=True)


class VectorDBServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.AddArticles,
                    request_deserializer=vector__db__pb2.AddArticlesRequest.FromString,
                    response_serializer=vector__db__pb2.AddArticlesResponse.SerializeToString,
            ),
            'GetArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticles,
                    request_deserializer=vector__db__pb2.GetArticlesRequest.FromString,
                    response_serializer=vector__db__pb2.GetArticlesResponse.SerializeToString,
            ),
            'RemoveArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveArticles,
                    request_deserializer=vector__db__pb2.RemoveArticlesRequest.FromString,
                    response_serializer=vector__db__pb2.RemoveArticlesResponse.SerializeToString,
            ),
            'UpdateArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticles,
                    request_deserializer=vector__db__pb2.UpdateArticlesRequest.FromString,
                    response_serializer=vector__db__pb2.UpdateArticlesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vector_db.VectorDBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorDBService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/AddArticles',
            vector__db__pb2.AddArticlesRequest.SerializeToString,
            vector__db__pb2.AddArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/GetArticles',
            vector__db__pb2.GetArticlesRequest.SerializeToString,
            vector__db__pb2.GetArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/RemoveArticles',
            vector__db__pb2.RemoveArticlesRequest.SerializeToString,
            vector__db__pb2.RemoveArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vector_db.VectorDBService/UpdateArticles',
            vector__db__pb2.UpdateArticlesRequest.SerializeToString,
            vector__db__pb2.UpdateArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
